services:
  app:
    container_name: cms-api
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DB_NAME=cms
      - MONGO_AUTH_SOURCE=admin
      - JWT_SECRET=your_jwt_secret
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - cms-network

  mongo:
    container_name: cms-mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    networks:
      - cms-network

volumes:
  mongo-data:

networks:
  cms-network:
    driver: bridge